#!/bin/bash

test/runtests $*

TIMEFORMAT=$' (%2lR real)'

pivotSplits="minimum median maximum gcd indep"
pivotActions="hilbert"

labelSplits="$pivotSplits maxlabel varlabel minlabel"
labelActions="irrdecom assoprimes alexdual"

frobSplits="frob $pivotSplits"
frobActions="frob"

for action in $labelActions;
do
  echo
  echo "*** $action"
  cd test/$action
  for split in $labelSplits
  do
    echo -n " $split "
    ./runtests $* -split $split
    if [ $? != 0 ]; then exit 1; fi
    echo
  done
  cd ../..
done

for action in $pivotActions;
do
  echo
  echo "*** $action"
  cd test/$action
  for split in $pivotSplits
  do
    echo -n " $split "
    ./runtests $* -split $split
    if [ $? != 0 ]; then exit 1; fi
    echo
  done
  cd ../..
done

for action in $frobActions;
do
  echo
  echo "*** $action"
  cd test/$action
  for split in $frobSplits
  do
    echo -n " $split "
    ./runtests $* -split $split
    if [ $? != 0 ]; then exit 1; fi
    echo
  done
  cd ../..
done
