#!/bin/bash

TIMEFORMAT=$' (%2lR real)'

echo -n "decom (slice, split=label): "
cd test/decom
time ./runtests -slice on -split label
cd ../..

echo -n "decom (slice, split=minart): "
cd test/decom
time ./runtests -slice on -split minart
cd ../..

echo -n "decom (label): "
cd test/decom
time ./runtests -slice off -independence off
cd ../..

echo -n "frob (slice): "
cd test/frob
time ./runtests -slice on
cd ../..

echo -n "frob (label): "
cd test/frob
time ./runtests -slice off
cd ../..

echo -n "intersect: "
cd test/intersect
time ./runtests
cd ../..

echo -n "assprimes: "
cd test/assprimes
time ./runtests
cd ../..

echo -n "minimize: "
cd test/minimize
time ./runtests
cd ../..
