#!/bin/bash

if [ "$1" = "_few" ]; then
  testLevel="few";
  shift;
else
  testLevel="normal"
fi

TIMEFORMAT=$' (%2lR real)'

normalTests="dimension irrdecom hilbert primdecom intersect assoprimes \
             minimize alexdual radical frob maxstandard optimize"

specialTests="error idealFormats polyFormats latticeFormats internal"
params="$*"

runNormalTests () {
  action="$1"; shift;
  path="$1"; shift;
  cd test/$path;
  ../testScripts/runtests $action $params
  if [ $? != 0 ]; then exit 1; fi
  cd ../..;
}

for t in $normalTests; do
  echo -n "$t "

  runNormalTests $t specialIdeals
  if [ "$testLevel" = "few" ]; then
    if [ "$t" != "frob" ]; then
      echo;
	  continue;
    fi
  fi

  runNormalTests $t commonIdeals

  runNormalTests $t frob

  if [ -e "$t" ]; then
    runNormalTests $t $t
  fi

  echo
done

for t in $specialTests;
do
  echo -n "$t "
  cd test/$t
  ./runtests $*
  if [ $? != 0 ]; then exit 1; fi
  echo
  cd ../..
done

echo "All tests passed."
