#!/bin/bash

# This runs a test while providing diagnostic output on error.
# $1  The Frobby action to run (e.g. alexdual)
# $2  The input file
# $3  The reference output file
# $4+ Parameters to frobby
#
# If the output produced by Frobby does not match that from the
# reference output according to diff, then this is considered an
# error, diagnostics will be printed and the exit status will 1.
#
# Otherwise a dot '.' is printed and the exit status is 0.
#
# If $4 is _generate, then the output from Frobby is piped into the
# reference output file, overwriting any previous contents. It is
# recommended to manually inspect the output to check if it is
# correct.
#
# If $4 is _summary, then nothing will be printed on success, and a
# short summary line is printed on failure. In this case the exit
# status 0 zero even on failure. The intent of this is to get a
# summary of all failing tests, instead of getting detailed
# information on the first failure.

# This script is designed to be run from a sub-directory of where it
# resides.
frobby=../../bin/frobby
action="$1"
inputFile="$2"
referenceOutputFile="$3"

shift
shift
shift

idealCanon=0
if [ "$1" = "_idealCanon" ];
then
  idealCanon=1;
  shift;
fi

generate=0
if [ "$1" = "_generate" ];
then
  generate=1;
  shift;
fi

summary=0
if [ "$1" = "_summary" ];
then
  summary=1;
  shift;
fi

params="$*"

if [ $generate = 1 ]
then
  if [ "$inputFile" == "$referenceOutputFile" ];
  then
    exit 0;
  fi
  echo "***** Generating $referenceOutputFile";
  $frobby $action $params < $inputFile > $referenceOutputFile;
  exit 0
fi

if [ $idealCanon = 0 ];
then
  $frobby $action $params < $inputFile 2> /dev/null $canonCmd | \
    diff - $referenceOutputFile > /dev/null
else
  $frobby $action $params < $inputFile 2> /dev/null $canonCmd | \
    $frobby transform -canon 2>/dev/null | \
    diff - $referenceOutputFile > /dev/null
fi

if [ $? = 0 ];
then
  if [ $summary = 0 ];
  then
    echo -n .
  fi
  exit 0;
fi

if [ $summary = 1 ];
then
  echo "Error on $action: $inputFile -> $referenceOutputFile";
  exit 0;
fi

echo
echo
echo "***** Encountered failure on output $referenceOutputFile. Input was:"
cat $inputFile

echo "***** Reference output:"
cat $referenceOutputFile

echo "***** Standard output from Frobby:"
if [ $idealCanon = 0 ];
then
  $frobby $action $params < $inputFile 2>/dev/null
else
  $frobby $action $params < $inputFile 2>/dev/null | \
    $frobby transform -canon 2>/dev/null
fi

echo "***** Error output from Frobby:"
$frobby $action $params < $inputFile > /dev/null

echo
echo "***** A test $action: $inputFile -> $referenceOutputFile failed."
echo "  $frobby $action $params < $inputFile"
if [ $idealCanon = 1 ];
then
  echo "    | $frobby transform -canon 2>/dev/null"
fi

exit 1
