#!/bin/bash

testName="$1"
shift

inputFile="$testName.test"
params="$*"

outputFile="$testName.radical"
../testhelper transform $inputFile $outputFile $params -canon -radical -minimize
if [ $? != 0 ]; then exit 1; fi
