#!/bin/bash

echo -n "1 " > $1.out.mat
wc $1 | sed "s/ *[0-9]* *\([0-9]*\) *.*/\1/" >> $1.out.mat
cat $1 >> $1.out.mat

4ti2/4ti2gmp groebner $1.out > /dev/null

cat $1.out.gro $1 | bin/frobby frobgrob $2 $3 $4 $5 $6 $7 $8 $9
