#include "stdinc.h"
#include "IrreducibleDecomFacade.h"

#include "IrreducibleDecomParameters.h"
#include "BigIdeal.h"
#include "IOFacade.h"
#include "Strategies.h"
#include "LabelAlgorithm.h"
#include "VarNames.h"
#include "TermTranslator.h"

IrreducibleDecomFacade::
IrreducibleDecomFacade(bool printActions,
		       const IrreducibleDecomParameters& parameters):
  Facade(printActions),
  _parameters(parameters) {
}

void IrreducibleDecomFacade::
computeIrreducibleDecom(BigIdeal& ideal, ostream& out) {
  beginAction("Computing irreducible decomposition using label algorithm.");

  ASSERT(ideal.getNames().getVarCount() >= 1);
  
  // Special case for when the ideal is all of the ring, i.e. minimally
  // generated by the monomial 1. Also special case for when there is only
  // one variable.
  if (ideal.getNames().getVarCount() == 1 ||
      (ideal.size() == 1 &&
       ideal[0] == vector<mpz_class>(ideal.getNames().getVarCount()))) {
    IOFacade ioFacade(false);
    ioFacade.writeIdeal(out, ideal);
    return;
  }

  TermTree* tree;
  TermTranslator* translator;
  ideal.buildAndClear(tree, translator, false);

  Strategy* strategy = new DecompositionStrategy
    (&out, ideal.getNames(), ideal.getNames().getVarCount(),
     translator, false);
  runAlgorithm(tree, translator, strategy);

  endAction();
}

void IrreducibleDecomFacade::
computeFrobeniusNumber(const vector<mpz_class>& instance,
		       BigIdeal& ideal, 
		       mpz_class& frobeniusNumber) {
  beginAction
    ("Optimizing over irreducible decomposition using label algorithm.");

  TermTree* tree;
  TermTranslator* translator;
  ideal.buildAndClear(tree, translator, false);

  Strategy* strategy = new FrobeniusStrategy
    (instance, &frobeniusNumber, ideal.getNames().getVarCount(),
     translator, _parameters.getUseBound());
  runAlgorithm(tree, translator, strategy);

  endAction();
}

// All parameters are deleted.
void IrreducibleDecomFacade::
runAlgorithm(TermTree* tree, TermTranslator* translator, Strategy* strategy) {
  ASSERT(strategy != 0);

  // Set up the combined strategy
  vector<Strategy*> strategies;
  strategies.push_back(strategy);

  if (_parameters.getDoBenchmark())
    strategy = addStrategy(strategies, strategy, new BenchmarkStrategy());

  if (_parameters.getPrintProgress())
    strategy = addStrategy(strategies, strategy, new PrintProgressStrategy());

  if (_parameters.getPrintStatistics())
    strategy = addStrategy
      (strategies, strategy,
       new StatisticsStrategy(tree->getDimension()));

  if (_parameters.getPrintDebug())
    strategy = addStrategy(strategies, strategy, new PrintDebugStrategy());

  if (_parameters.getSkipRedundant()) {
    strategy = 
      new SkipRedundantStrategy(strategy, tree->getDimension());
    strategies.push_back(strategy);
  }

  // Run algorithm
  LabelAlgorithm algo(strategy, tree, _parameters.getUsePartition());

  // Clean up afterwards
  for (vector<Strategy*>::iterator it = strategies.begin();
       it != strategies.end(); ++it)
    delete *it;

  delete tree;
  delete translator;
}

Strategy* IrreducibleDecomFacade::
addStrategy(vector<Strategy*>& strategies,
	    Strategy* oldStrategy,
	    Strategy* newStrategy) {
  ASSERT(oldStrategy != 0);
  ASSERT(newStrategy != 0);
  
  Strategy* composite = new CompositeStrategy(oldStrategy, newStrategy);

  strategies.push_back(oldStrategy);
  strategies.push_back(composite);

  return composite;
}
