#!/usr/bin/env bash

profileFile=../../bin/profile.hilbert
frobby=../../bin/frobby
if [ "$1" = "_profile" ];
then
  rm -f gmon.out
fi

./benchHelper hilbert nearGenericV15G50.test $*
./benchHelper hilbert nearGenericV15G50.test $*
./benchHelper hilbert n8d30.test $*

if [ "$1" = "_profile" ];
then
  gprof $frobby > $profileFile
  rm -f gmon.out
fi
