#!/usr/bin/env bash

frobby=../../bin/frobby
TIMEFORMAT="%1Us (user CPU time)"

echo -n "alexdual nearGenericV15G50 "
time $frobby irrdecom < nearGenericV15G50.test \
  -oformat null $*

echo -n "alexdual sqfreeV25G1000    "
time $frobby irrdecom < sqfreeV25G1000.test \
  -oformat null $*

echo -n "alexdual n11d11            "
time $frobby alexdual < n11d11.test \
  -oformat null $*
