#!/usr/bin/env bash

profileFile=../../bin/profile.optimize
frobby=../../bin/frobby
if [ "$1" = "_profile" ];
then
  rm -f gmon.out
fi

./benchHelper optimize nearGenericV15G50.test $* \
  -displayLevel 0 -displayValue off

./benchHelper optimize sqfreeV25G1000.test $* \
  -displayLevel 0 -displayValue off

cat n11d11.test n11d11 > /tmp/n11d11.test
./benchHelper optimize /tmp/n11d11.test $* \
  -displayLevel 0 -displayValue off -chopFirstAndSubtract
rm -f /tmp/n11d11.test

if [ "$1" = "_profile" ];
then
  gprof $frobby > $profileFile
  rm -f gmon.out
fi
