#!/usr/bin/env bash

echo -en "\n********************************\nOptions: $*\nDate: "| \
  tee /tmp/benchHeader1
date|tee /tmp/benchHeader2
echo

./run_alexdual_bench $* 2>&1|tee /tmp/benchAlexdual
./run_hilbert_bench $* 2>&1|tee /tmp/benchHilbert
./run_optimize_bench $* 2>&1|tee /tmp/benchOptimize

echo|cat /tmp/benchHeader1 /tmp/benchHeader2 - \
  /tmp/benchAlexdual /tmp/benchHilbert /tmp/benchOptimize >> log
