#!/bin/bash

# Note that not specifying the input format tests the format
# autodetection. We first produce output in all formats with no other
# transformation, and we end with producing canonical output without
# specifying the output format.

testName="$1"
shift

inputFile="$testName.test"
oformats="m2 4ti2 monos newmonos singular cocoa4"
params="$*"

for oformat in $oformats; do
  # Test format conversion to $oformat
  outputFile="$testName.$oformat";
  ../testhelper transform $inputFile $outputFile $params -oformat $oformat;
  if [ $? != 0 ]; then exit 1; fi

  # Test same-format transform
  ../testhelper transform $outputFile $outputFile $params;
  if [ $? != 0 ]; then exit 1; fi
done

# Test canonicalization of input
outputFile="$testName.canon";
../testhelper transform $inputFile $outputFile $params -canon
