#!/bin/bash

../../$frobby transform $2 $3 $4 $5 $6 $7 -oformat m2 < $1 2> /dev/null| diff - $1.m2

if [ $? != 0 ]
then
  echo
  echo "Test $1 failed (monos to m2)"
  exit 1
fi

../../$frobby transform $2 $3 $4 $5 $6 $7 -oformat monos < $1.m2 2> /dev/null| diff - $1

if [ $? != 0 ]
then
  echo
  echo "Test $1 failed (m2 to monos)"
  exit 1
fi



../../$frobby transform $2 $3 $4 $5 $6 $7 -oformat newmonos < $1 2> /dev/null| diff - $1.nm

if [ $? != 0 ]
then
  echo
  echo "Test $1 failed (monos to newmonos)"
  exit 1
fi



../../$frobby transform $2 $3 $4 $5 $6 $7 -oformat monos < $1.nm 2> /dev/null| diff - $1

if [ $? != 0 ]
then
  echo
  echo "Test $1 failed (newmonos to monos)"
  exit 1
fi




../../$frobby transform $2 $3 $4 $5 $6 $7 -oformat 4ti2 < $1 2> /dev/null| diff - $1.4ti2

if [ $? != 0 ]
then
  echo
  echo "Test $1 failed (monos to 4ti2)"
  exit 1
fi


../../$frobby transform $2 $3 $4 $5 $6 $7 -oformat monos < $1.4ti2 2> /dev/null| diff - $1.4ti2.monos

if [ $? != 0 ]
then
  echo
  echo "Test $1 failed (4ti2 to monos)"
  exit 1
fi


echo -n .
