#!/bin/bash

testName="$1"
shift

inputFile="$testName.test"
params="$*"

outputFile="$testName.irrdecom"
../testhelper irrdecom $inputFile $outputFile $params -encode -canon
if [ $? != 0 ]; then exit 1; fi

exit 0

#!/bin/bash

../../$frobby irrdecom -encode $2 $3 $4 $5 $6 $7 < $1 2> /dev/null | \
../../$frobby transform -canon 2> /dev/null| diff - $1.ref

if [ $? != 0 ]
then
  echo
  echo Test $1 failed
  exit 1
fi

echo -n .
