#!/usr/bin/env sh

frobby=../../bin/frobby
testhelper=../testScripts/testhelper
test="$1"
shift

if [ "$1" = "_full" ];
then
  shift;

  # Check -canon agrees with transform.
  $testhelper transform $test.assoprimes $test.assoprimes -canon
  if [ $? != 0 ]; then exit 1; fi

  # Check that radical of Alexander dual equals associated primes.
  $testhelper transform $test.alexdual $test.assoprimes \
    -radical -unique -canon
  if [ $? != 0 ]; then exit 1; fi
fi

$testhelper assoprimes $test.*test $test.assoprimes $* -canon
