#!/bin/bash

# Note that not specifying the input format tests the format
# autodetection. We first produce output in all formats with no other
# transformation, and we end with producing canonical output without
# specifying the output format.

testhelper=../testScripts/testhelper
testName="$1"
shift

formats="m2 cocoa4 4ti2 singular"

if [ "$1" = "_full" ];
then
  shift;

  for format in $formats; do
    # Test same-format transform.
	$testhelper ptransform $testName.$format $testName.$format $*;
	if [ $? != 0 ]; then exit 1; fi

    # And again with specified formats.
	$testhelper ptransform $testName.$format $testName.$format $* \
      -iformat $format -oformat $format
	if [ $? != 0 ]; then exit 1; fi
  done

  # Test same-format transform on canon.
  $testhelper ptransform $testName.canon $testName.canon $*;
  if [ $? != 0 ]; then exit 1; fi
  
  # And again with -canon option.
  $testhelper ptransform $testName.canon $testName.canon $* -canon;
  if [ $? != 0 ]; then exit 1; fi
fi

for format in $formats; do
  # Test format conversion to $format
  $testhelper ptransform $testName.test $testName.$format $* -oformat $format;
  if [ $? != 0 ]; then exit 1; fi
done

# Test canonicalization of input
$testhelper ptransform $testName.test $testName.canon $* -canon
