#!/bin/bash

testName="$1"
shift

if [ ! -e "$testName.frobInstance" ]; then exit 0; fi

if [ "$1" = "_full" ]; then
  shift;
fi

inputFile="$testName.test $testName.frobInstance"
outputFile="$testName.frobNumber"

../testScripts/testhelper frobgrob "$inputFile" $outputFile $*
if [ $? != 0 ]; then exit 1; fi
