#!/bin/bash

testName="$1"
shift

inputFile="$testName.test"
params="$*"

outputFile="$testName.intersection"
../testhelper intersection $inputFile $outputFile $params -canon
if [ $? != 0 ]; then exit 1; fi
