#!/bin/bash

../../$frobby intersect < $1.test 2> /dev/null -oformat monos | \
../../$frobby transform -canon 2> /dev/null| diff - $1.ref

if [ $? != 0 ]
then
  echo
  echo Test $1 failed
  exit 1
fi

echo -n .
