#!/bin/bash

testName="$1"
shift

inputFile="$testName.test"
params="$*"

outputFile="$testName.multi"
../testhelper hilbert $inputFile $outputFile $params -canon
if [ $? != 0 ]; then exit 1; fi

outputFile="$testName.uni"
../testhelper hilbert $inputFile $outputFile $params -univariate -canon
if [ $? != 0 ]; then exit 1; fi
