#!/bin/bash

../../$frobby genfrob $* > random 2> /dev/null

echo -n "1 " > random.out.mat
wc random | sed "s/ *[0-9]* *\([0-9]*\) *.*/\1/" >> random.out.mat
cat random >> random.out.mat

../../4ti2/4ti2gmp groebner random.out > /dev/null
rm random.out.mat

cat random | ../../$frobby frobdyn > random.ref 2> /dev/null
