#!/bin/bash

while true
do
  ./makerandom
  ./runtest random.frob

  if [ $? != 0 ]
  then
    mv random.frob $1
    mv random.frob.out.gro $1.out.gro
    mv random.frob.ref $1.ref
    exit 1
  fi
done
