#!/bin/bash

testName="$1"
shift

inputFile="$testName.out.gro $testName"
params="$*"


outputFile="$testName.ref"
../testScripts/testhelper frobgrob "$inputFile" $outputFile $params
if [ $? != 0 ]; then exit 1; fi
exit 0
