#!/bin/bash

testName="$1"
shift

inputFile="$testName.test"
params="$*"

outputFile="$testName.minimize"
../testhelper transform $inputFile $outputFile $params -canon -minimize
if [ $? != 0 ]; then exit 1; fi
