#!/bin/bash

test="$1"
shift

../testhelper hilbert $test.test $test.multi $* -canon -oformat m2
if [ $? != 0 ]; then exit 1; fi

../testhelper hilbert $test.test $test.uni $* -univariate -canon -oformat m2
if [ $? != 0 ]; then exit 1; fi
