#!/usr/bin/env sh

frobby=../../bin/frobby
testhelper=../testhelper
test="$1"
shift

if [ "$1" = "_full" ];
then
  shift;

  # Check -canon agrees with transform.
  $testhelper transform $test.alexdual $test.alexdual -canon
  if [ $? != 0 ]; then exit 1; fi

  # Check that double dual on the same point is identity.
  $frobby transform < `ls $test.*test` > /tmp/$test.test \
    -canon -minimize 2>/dev/null
  $frobby analyze -lcm < `ls $test.*test` 2>/dev/null | \
    cat $test.alexdual - > /tmp/$test.dual

  $testhelper alexdual /tmp/$test.dual /tmp/$test.test $* -canon
  if [ $? != 0 ]; then exit 1; fi

  rm /tmp/$test.test /tmp/$test.dual
fi

$testhelper alexdual $test.*test $test.alexdual $* -canon
