#!/usr/bin/env sh

frobby=../../bin/frobby
testhelper=../testhelper
test="$1"
shift

if [ "$1" = "_full" ];
then
  shift;

  # Check -canon agrees with transform on output
  $testhelper transform $test.primdecom $test.primdecom $* -canon
  if [ $? != 0 ]; then exit 1; fi

  # TODO: get rid of the need for setting the oformat and checking for those
  # tests where the primdecom output is empty.
  if [ "$test" != "e15" ]; then
  if [ "$test" != "e2" ]; then
  if [ "$test" != "e3" ]; then
  if [ "$test" != "e12" ]; then
  if [ "$test" != "e8" ]; then
  if [ "$test" != "e13" ]; then
  if [ "$test" != "e4" ];
  then
    # Check that intersection is inverse of primdecom.
    $frobby transform < `ls $test.*test` > /tmp/$test.test \
      -canon -minimize 2>/dev/null
    $testhelper intersect $test.primdecom /tmp/$test.test $* -canon
    if [ $? != 0 ]; then exit 1; fi
    rm /tmp/$test.test
  fi fi fi fi fi fi fi
fi

$testhelper primdecom $test.*test $test.primdecom $* -canon
if [ $? != 0 ]; then exit 1; fi
