#!/usr/bin/env sh

test="run_$1_test"
shift

for t in `ls -S -r *.test`
do
  ./$test `basename $t .test` $*
  if [ $? != 0 ]; then exit 1; fi
done

if [ "$1" = "_full" ];
then
  for t in `ls -S -r *.fulltest`
  do
    ./$test `basename $t .fulltest` $*
    if [ $? != 0 ]; then exit 1; fi
  done
fi
