#!/bin/bash

./frobgrob w 2> /dev/null > /dev/null
cat w.out.gro w.out.lat|bin/frobby lata 2>/dev/null > /dev/null
f=$?
if [ $f == 2 ]; then echo "not generic"; exit 0; fi
if [ $f != 0 ]; then echo "found counterexample"; cat w.out.gro w.out.lat|bin/frobby lata > w.ana; exit $f; fi
echo generic
exit 0;
