#!/bin/bash

digits=4
entries=4

for (( c=1; c<=1000000; c++ )) do
  echo -n "try $c. ($entries entries of $digits digits)  ";
  ../bin/frobby genfrob -entryCount $entries -maxEntryDigits $digits > ../tmp/w 2>/dev/null;
  ./lata ../tmp/w;
  if [ $? != 0 ]; then echo "found one!"; exit 42; fi
done
