#!/bin/bash

../../$frobby genideal -varCount 3 -genCount 3 > /tmp/as_input

../../$frobby assoprimes < /tmp/as_input -alg irrdecom 2> /dev/null | \
../../$frobby format -canon 2> /dev/null > /tmp/as_irrdecom

../../$frobby assoprimes < /tmp/as_input -alg uwe 2> /dev/null | \
../../$frobby format -canon 2> /dev/null > /tmp/as_uwe

diff /tmp/as_uwe /tmp/as_irrdecom

if [ $? != 0 ]
then
  echo
  echo Test $1 failed
  exit 1
fi

rm /tmp/as_input
rm /tmp/as_uwe
rm /tmp/as_irrdecom

echo -n .
