#!/bin/bash

testName="$1"
shift

inputFile="$testName.test"
params="$*"

outputFile="$testName.assoprimes"
../testhelper assoprimes $inputFile $outputFile $params -canon
if [ $? != 0 ]; then exit 1; fi
