#!/bin/bash

cd ../../scripts/

./m2-hilbert-multi ../test/hilbert/$1.test /tmp/t
../bin/frobby ptransform -canon < /tmp/t > /tmp/t2
../bin/frobby ptransform -canon < ../test/hilbert/$1.multi > /tmp/t3
diff /tmp/t2 /tmp/t3
if [ $? != 0 ]; then exit 1; fi

./m2-hilbert-uni ../test/hilbert/$1.test /tmp/t
../bin/frobby ptransform -canon < /tmp/t > /tmp/t2
../bin/frobby ptransform -canon < ../test/hilbert/$1.uni > /tmp/t3
diff /tmp/t2 /tmp/t3
if [ $? != 0 ]; then exit 1; fi
